"""
飞书推送服务 — 支持 Webhook 和 Bot API
"""
from __future__ import annotations
from typing import Dict, Any
import httpx

from push.base import PushService, PushResult


class FeishuPushService(PushService):
    """通过飞书 Webhook 或 Bot API 发送推送。"""
    channel_name = "feishu"

    def validate_config(self, config: Dict[str, Any]) -> bool:
        return bool(config.get("feishu_webhook"))

    async def send(self, title: str, content: str, config: Dict[str, Any]) -> PushResult:
        if not self.validate_config(config):
            return PushResult(
                success=False,
                channel=self.channel_name,
                message="飞书 Webhook 未配置",
            )

        webhook = config["feishu_webhook"]
        text_content = self._strip_markdown(content)

        # 飞书 Webhook 消息体
        payload = {
            "msg_type": "interactive",
            "card": {
                "header": {
                    "title": {"tag": "plain_text", "content": f"📋 {title}"},
                    "template": "orange",
                },
                "elements": [
                    {"tag": "div", "text": {"tag": "lark_md", "content": self._truncate(text_content, 4000)}},
                    {"tag": "hr"},
                    {"tag": "note", "elements": [{"tag": "plain_text", "content": "Generated by GoldTo Intelligence"}]},
                ],
            },
        }

        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                resp = await client.post(webhook, json=payload)
                data = resp.json()

            if data.get("code") == 0:
                return PushResult(
                    success=True,
                    channel=self.channel_name,
                    message="飞书推送成功",
                    detail={"webhook": webhook[:30] + "..."},
                )
            else:
                return PushResult(
                    success=False,
                    channel=self.channel_name,
                    message=f"飞书返回错误: {data.get('msg', 'unknown')}",
                    detail={"code": data.get("code")},
                )

        except Exception as e:
            return PushResult(
                success=False,
                channel=self.channel_name,
                message=f"飞书推送失败: {str(e)}",
            )

    def _strip_markdown(self, text: str) -> str:
        """去除 Markdown 标记，转换为飞书 Lark Markdown 兼容格式。"""
        import re
        text = re.sub(r"#+\s*", "", text)
        text = re.sub(r"\*\*|__", "**", text)
        text = re.sub(r"\*|_", "", text)
        text = re.sub(r"`{1,3}[^`]*`{1,3}", "", text)
        text = re.sub(r"!\[.*?\]\(.*?\)", "", text)
        text = re.sub(r"\[([^\]]+)\]\(([^\)]+)\)", r"[\1](\2)", text)
        return text.strip()
